@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteCategoryCommandParser" as DeleteCategoryCommandParser LOGIC_COLOR
participant "d:DeleteCategoryCommand" as DeleteCategoryCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
participant "personToEdit:Person" as Person MODEL_COLOR
participant "e:Entry" as Entry MODEL_COLOR
end box

[-> LogicManager : execute("deleteCategory 1 c/Clan")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("deleteCategory 1 c/Clan")
activate AddressBookParser

create DeleteCategoryCommandParser
AddressBookParser -> DeleteCategoryCommandParser
activate DeleteCategoryCommandParser

DeleteCategoryCommandParser --> AddressBookParser
deactivate DeleteCategoryCommandParser

AddressBookParser -> DeleteCategoryCommandParser : parse("1 c/Clan")
activate DeleteCategoryCommandParser

create DeleteCategoryCommand
DeleteCategoryCommandParser -> DeleteCategoryCommand
activate DeleteCategoryCommand

DeleteCategoryCommand --> DeleteCategoryCommandParser :
deactivate DeleteCategoryCommand

DeleteCategoryCommandParser --> AddressBookParser : d
deactivate DeleteCategoryCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCategoryCommandParser -[hidden]-> AddressBookParser
destroy DeleteCategoryCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> DeleteCategoryCommand : execute(m)
activate DeleteCategoryCommand


DeleteCategoryCommand -> Person
activate Person

Person -> Entry : getEntry("Clan")
activate Entry

Entry --> Person : e
deactivate Entry

Person -> Entry : deleteEntry(e)
activate Entry

Entry --> Person
deactivate Entry

Person --> DeleteCategoryCommand
deactivate Person

DeleteCategoryCommand -> Model
activate Model

Model --> DeleteCategoryCommand
deactivate Model

create CommandResult
DeleteCategoryCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCategoryCommand
deactivate CommandResult

DeleteCategoryCommand --> LogicManager : r
deactivate DeleteCategoryCommand

[<--LogicManager
deactivate LogicManager
@enduml
