@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":CommandHistory" as CommandHistory MODEL_COLOR
end box

[-> Model : undo()
activate Model

Model -> CommandHistory : setAddressBook(commandHistory)
activate CommandHistory

CommandHistory --> Model :
deactivate CommandHistory

[<-- Model
deactivate Model

@enduml
